defaults:
  - dataset: cifar100
  - model: cifar100
  - optimizer: sgd
  - trainer: default
  - checkpoint: default
  - _self_


project: "cifar100-alexnet"
run_name: "lclr-average-pool"


trainer:
  max_epochs: 5
optimizer:
  lr: 0.1
  scheduler:
    milestones: [30, 40, 50]
    gamma: 0.1
dataset:
  batch_size: 256

seed: 42